spring:
  application:
    name: demo
  datasource:
    url: jdbc:h2:mem:db;
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
    initialization-mode: always
    platform: h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  h2:
    console:
      enable: true

